### ISSUE TITLE
New Device Type - Thermostat

### ISSUE THREAD

**Issue by kurtdwarwick** [toddaustin07/MQTTDevices#1]
Hi

Thank you so much for creating this awesome driver. 

Would you consider adding a thermostat to the mix? I am currently using HomeKit and am exposing a Shelly 1 + Temp Sensor as a Thermostat, through Homebridge.

However, I am looking to move towards ST now that local processing and Matter are a real thing, but I can’t see any other way to do this without using your driver.

Thanks so much!

Kurt

**Comment by toddaustin07** [comment]
Hi there.  Glad you find the driver useful.  Yes, I could certainly add thermostat to the list!  There are a few others that have been requested as well, but I will get to it eventually - hopefully in a month or 2.

Are you aware that I have a Shelly Edge driver that supports the Shelly 1 - so that you would be able to integrate the device directly and without dependence on the cloud.

**Comment by toddaustin07** [comment]
Hi there - wanted to follow up with you on adding a thermostat device.  I have some questions for you:

Thermostat devices can be pretty complex with multiple SmartThings capabilities/controls.  For example, the virtual thermostat in my vEdge driver has these elements:

* current operating state
* change mode
* change fan mode
* set temperature setpoint - heating
* set temperature setpoint - cooling
* current temperature

Can you tell me a bit more about the MQTT topics and messages that you would be sending to the SmartThings driver?  For example, it could be one topic for the device, with a JSON message payload with the various elements.  Or it could be separate topics for the various elements, with a JSON or string message format.  How you would need this to work will determine how I'd need to implement it.

Also, if your 'thermostat' is really just an on/off switch using the Shelly 1with a temperature sensor, have you considered using 
my Shelly driver for Gen1 Shelly devices?

Another approach is to enable MQTT on your Shelly device and we could see if we could get it to work with my MQTT Devices driver.

**Comment by toddaustin07** [comment]
FYI, I've also just added a temperature device to the driver.

**Comment by toddaustin07** [comment]
Closing this issue as original poster has not responded.  Feel free to re-open if needed.
