### ISSUE TITLE
Light with Dimmer

### ISSUE THREAD

**Issue by jtwillse** [toddaustin07/MQTTDevices#3]
Love this implementation. Has opened up a bunch for me. Would it be possible to create a light with a dimmer. Right now, the existing MQTT dimmer device is not recognized as a switch by Smartthings, so you can't do things like mirroring.

**Comment by toddaustin07** [comment]
Hi there.  Sorry for the delay in responding.  If I added a switch to the dimmer device, would that be sufficient?  What would the MQTT messages contain;  only dimmer values or also on/off?  Or would we assume 0=off and >0=on?

**Comment by jtwillse** [comment]
I'm not totally sure of the behavior of the smart lighting app, but when I
look at other light devices on smartthings they seem to only have a switch
(off/on) and dimmer property. So, adding a swtich channel to the dimmer
device might be enough. I don't know if there is some other metadata
somewhere that also identifies it as a light/switch. I appreciate the
response and the resource for the Smartthings community!

**Comment by toddaustin07** [comment]
Are you looking to connect an external device via MQTT and have a SmartThings device reflect its state?  Or are you needing the other way around where the SmartThings device is publishing states OUT to MQTT for a device to act on?

**Comment by jtwillse** [comment]
I'm using MQTT to connect to a virtual device in openHab. So, essentially I
use a virtual device on both sides of MQTT to allow me to use my openHab as
a simple dashboard for visitors to control my Smartthings. So, publishing
and receiving states is needed on both sides of the MQTT connection. It
currently works like a charm with simple switches.

Right now, I use a simple switch on both sides to trigger scenes and
routines in Smartthings. But, if I can get mirroring established (Smart
Lighting App), then I can directly control some of my key smartthings
lighting devices from openHab. Smartthings to my knowledge has no easy way
to make a guest dashboard, with no login or download of apps required. My
solution is very hacky! But it allows me to use an NFC tag in the house to
get anyone who comes in and connects to my local network a URL to have some
basic control.

**Comment by toddaustin07** [comment]
The current dimmer device is in fact defined as a switch category device, so it's perplexing why the SmartLighting app is not letting you select it.  I guess it is looking for devices that only have a switch capability included.  So I'll try adding it in the device profile and see if that solves that issue.

But we also have to work out exactly what happens with the switch state when the dimmer is adjusted.  I think most light devices keep the switch independent of the dimmer value, but I've also seen where you could have the switch automatically turn off if dimmer is set to 0, and turn on for any dimmer value > 0.  

If we keep the dimmer and switch completely independent, then I'll have to also add separate topics for subscribing and publishing.  I don't know if whatever device you are working with is sending just dimmer values or also switch state on/off values?

Can you comment?

**Comment by jtwillse** [comment]
The way my virtual devices are defined, I can set an arbitrary number of
channels. I am defining my switches to send a "on" "off" payload. My dimmer
sends a 0 to 100. I can define rules to comply with however the light works
in smartthings.

In the smartthings app, most devices seem to have an on/off switch that is
independent of dimmer. So, if you turn a device off, then back on, the
light returns to its last dimmed state. The switch though also seems
reactive to dimmer level, so that a change in dimmer state creates "on"
status, unless that change is to 0. Changing a light dimmer to 0 does not
seem to trigger a device off status.

**Comment by toddaustin07** [comment]
I've looked at how Alexa is dealing with dimmers and you described it exactly.  If you change the dimmer level at all, it turns on the switch.  But you can turn on and off the switch and it does not affect the dimmer.  

Give me a few days and I'll have the switch added.

**Comment by toddaustin07** [comment]
I've added a switch to dimmer devices in the latest driver that has just been pushed out.  Give it a try and let me know if it solves your need.  You will have to create a new dimmer device to get the switch.

New driver version is:  **2022-12-17T00:45:50.022631669**

**Comment by jtwillse** [comment]
Thanks Todd! I will try it this week.

**Comment by jtwillse** [comment]
Todd,

Sorry this got away from me over the holiday season. I am back at it, to
try the driver. I uninstalled the diver device from my app, but when I
click on uninstall from the channel (so I can install the newer version) i
get an error that says driver in use. Do you think that I need to delete
all previously created mqtt devices too?

Thanks

-john
[image: image.png]

**Comment by eoware** [comment]
@toddaustin07

It looks like the on/off switch added to the dimmer emits SmartThings events but doesn't publish the on/off MQTT message for the switch.
