### ISSUE TITLE
MQTT Lock State vs action

### ISSUE THREAD

**Issue by lap33733** [toddaustin07/MQTTDevices#4]
Some locks publish different message for state versus message for action, there should be two different values for get state and publish action. As for example my lock publishes "Locked" for state and "Lock" for action

**Comment by toddaustin07** [comment]
Hello - thanks for your suggestion.  I have implemented it in the latest driver that I've just pushed out!

You'll have to create a new lock device to see the new configuration options in device Settings.

Driver version:  **2022-12-17T00:45:50.022631669**

**Comment by lap33733** [comment]
Many tanks
