### ISSUE TITLE
Device Creator issues: Capitalization of data fields, confusing status, unclear if actually connecting to to MQTT... help?

### ISSUE THREAD

**Issue by kubycsolutions** [toddaustin07/MQTTDevices#6]
I've been unable to get MQTT Device Creator V1.7 to talk to the Mosquitto instance running on my Pi 3B (not Plus).  

I first tried without authentication; got unending status of Connecting. Yes, I checked that the phone, the ST hub it's talking to, and the Mosquitto instance are all connected to the same subnet (since I've had problems in the past when your code was trying to cross subnets).

OK, try with authentication.... and we have what looks like a code bug. The userID I've set up via mosquitto_passwd is **keshlamMosq**. The Device Creator Settings screen will not let me enter that userID; no matter what I do, it insists upon uppercase first letter, **KeshlamMosq**.  

This fails. Status never gets out of **Connecting...**.

I am guessing that Mosquitto, like most non-Windows (ie, non-dumbed-down) software, is case-sensitive and that this is why the attempt is failing. At the very least, the Device Creator should not be taking liberties with capitalization; if we type it oDdLY, please accept that we meant to type it oDdLY!

Please let me know if there's anything I can do to help you reproduce or analyze the problem, or if there's a solution available I could test.

[I should note that this is once again on the network whose SSID is "Casa delGato", with a space. That space upset some of your earlier SmartThing-on-Raspberry-Pi setup code, but since the MQTT configuration is in terms of IP address and doesn't deal with wireless setup, I wouldn't have expected that to be a problem. Just mentioning it to cover all the basis.]

Thanks, as always, for all the work you've put into trying to make the SmartThings universe extensible to custom solutions!

(BTW, not sure I told you, but I found a cure for Pi Zero W's being so indecently hard to SSH into: In **ssh_config** and **sshd_config**, add a line saying **IPQoS 0x00** to allow packet retries. Apparently the Zero W's hardware just can't keep up with the normally assumed Quality of Service settings. "The impressive thing is that the bear dances at all." Just don't think too much about how dancing bears were trained.)

**Comment by kubycsolutions** [comment]
This may not actually be a capitalization problem.  Or it's that plus something else.

I tried adding KeshlamMosq to Mosquitto as a second userID. No change, still still says only **Connecting...**, not Connected. Tapping the Refresh button doesn't change that. 

BUT... the "All Devices" view shows it as **Connected**. So this may be a display glitch rather than an actual connection glitch. 

So I tried to create a Temperature device. The Device Creator screen says **Creating Device** and never changes, but, I get a notification from Alexa telling me **MQTT Temperature connected**, and the new device appears in the device list as Connected. 

I opened that device, went into its settings, and configured it as Test/temp and Test/tempset. (Again, you seem to be capitalizing the first letter whether I ask you to do that or not.). Turned on Publish. Back to the device screen, and status still reads **Not Subscribed** and I can't move the **Set Temperature** slider. Refresh doesn't change that, nor exiting and returning to the device screen.

I tried issuing **mosquitto_pub -t Test/temp -m "30"**, and nothing showed up on the temperature device screen. Again, refresh didn't help.

So at this point I'm really not sure where the process is breaking down, and I think I need help determining that.

**Comment by kubycsolutions** [comment]
Raised the question on https://community.smartthings.com/t/integration-solutions-using-mqtt/245186/464

**Comment by toddaustin07** [comment]
Hi - I'm quite delinquent in responding here, so my apologies.  I saw the conversation in the community topic regarding your use of network addresses that are outside the norm.

By now I'm sure you've also figured out the capitalization issue you were seeing when editing device Settings options:  This is purely an issue of the way the app DISPLAYS the field value.  For some reason it always capitalizes the first character of a text field.  You'll see if you actually edit the field again, that it is in fact NOT capitalized.  This is an SmartThings app anomaly, and nothing I can fix.

Please DM me on the community if you need more help.  Or you can use github if you prefer.  In either case, close this Issue when/if appropriate.

**Comment by kubycsolutions** [comment]
After a week of arm-wrestling my firewall into a "normal" private address range (error in NAT, not in ACLs where I expected it!), I do now have the device creator talking to my mosqitto server.

Thanks for the heads-up on capitalization being apparently but not necessarily real. I think I'd better stick with capitalizing the first part, just to reduce confusion.

Theoretically, temperature broadcast and listen (set and get) ought to cover the most essential initial controls for my experiment. There are a whole bunch of other parameters that could be exposed but these are enough to prototype with.

The pi that is running mosquitto is also connected to an X10 interface via the Heyu package. With a bit of glue code, that would let me take advantage of the pile of stuff I was using before home automation became smart home.

But I owe some time to Apache Xalan, which was put aside while I fought the firewall, so there may be another delay before I can report success going from ST to MQTT to Pi to IR to HVAC and back.

I'll let you know if I trip over my own feet again. Thanks again for all the work you've put into this; I'm well aware that my occasional grumbles are either my own confusion or nitpicking.


--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

() Plaintext Ribbon Campaign
/\ Stamp out HTML mail!
________________________________
